String shownumber(int number) {
  switch (number) {
    case 0:
      return 'Zero';
    case 1:
      return 'One';
    case 2:
      return 'Two';
    case 3:
      return 'Three';
    case 4:
      return 'Four';
    case 5:
      return 'Five';
    case 6:
      return 'Six';
    case 7:
      return 'Seven';
    case 8:
      return 'Eight';
    case 9:
      return 'Nine';
    case 10:
      return 'Ten';
    case 11:
      return 'Eleven';
    case 12:
      return 'Twelve';
    case 13:
      return 'Thirteen';
    case 14:
      return 'Fourteen';
    case 15:
      return 'Fifteen';
    case 16:
      return 'Sixteen';
    case 17:
      return 'Seventeen';
    case 18:
      return 'Eighteen';
    case 19:
      return 'Nineteen';
    case 20:
      return 'Twenty';
    case 21:
      return 'Twenty-one';
    case 22:
      return 'Twenty-two';
    case 23:
      return 'Twenty-three';
    case 24:
      return 'Twenty-four';
    case 25:
      return 'Twenty-five';
    case 26:
      return 'Twenty-six';
    case 27:
      return 'Twenty-seven';
    case 28:
      return 'Twenty-eight';
    case 29:
      return 'Twenty-nine';
    case 30:
      return 'Thirty';
    case 31:
      return 'Thirty-one';
    case 32:
      return 'Thirty-two';
    case 33:
      return 'Thirty-three';
    case 34:
      return 'Thirty-four';
    case 35:
      return 'Thirty-five';
    case 36:
      return 'Thirty-six';
    case 37:
      return 'Thirty-seven';
    case 38:
      return 'Thirty-eight';
    case 39:
      return 'Thirty-nine';
    case 40:
      return 'Forty';
    case 41:
      return 'Forty-one';
    case 42:
      return 'Forty-two';
    case 43:
      return 'Forty-three';
    case 44:
      return 'Forty-four';
    case 45:
      return 'Forty-five';
    case 46:
      return 'Forty-six';
    case 47:
      return 'Forty-seven';
    case 48:
      return 'Forty-eight';
    case 49:
      return 'Forty-nine';
    case 50:
      return 'Fifty';
    case 51:
      return 'Fifty-one';
    case 52:
      return 'Fifty-two';
    case 53:
      return 'Fifty-three';
    case 54:
      return 'Fifty-four';
    case 55:
      return 'Fifty-five';
    case 56:
      return 'Fifty-six';
    case 57:
      return 'Fifty-seven';
    case 58:
      return 'Fifty-eight';
    case 59:
      return 'Fifty-nine';
    case 60:
      return 'Sixty';
    case 61:
      return 'Sixty-one';
    case 62:
      return 'Sixty-two';
    case 63:
      return 'Sixty-three';
    case 64:
      return 'Sixty-four';
    case 65:
      return 'Sixty-five';
    case 66:
      return 'Sixty-six';
    case 67:
      return 'Sixty-seven';
    case 68:
      return 'Sixty-eight';
    case 69:
      return 'Sixty-nine';
    case 70:
      return 'Seventy';
    case 71:
      return 'Seventy-one';
    case 72:
      return 'Seventy-two';
    case 73:
      return 'Seventy-three';
    case 74:
      return 'Seventy-four';
    case 75:
      return 'Seventy-five';
    case 76:
      return 'Seventy-six';
    case 77:
      return 'Seventy-seven';
    case 78:
      return 'Seventy-eight';
    case 79:
      return 'Seventy-nine';
    case 80:
      return 'Eighty';
    case 81:
      return 'Eighty-one';
    case 82:
      return 'Eighty-two';
    case 83:
      return 'Eighty-three';
    case 84:
      return 'Eighty-four';
    case 85:
      return 'Eighty-five';
    case 86:
      return 'Eighty-six';
    case 87:
      return 'Eighty-seven';
    case 88:
      return 'Eighty-eight';
    case 89:
      return 'Eighty-nine';
    case 90:
      return 'Ninety';
    case 91:
      return 'Ninety-one';
    case 92:
      return 'Ninety-two';
    case 93:
      return 'Ninety-three';
    case 94:
      return 'Ninety-four';
    case 95:
      return 'Ninety-five';
    case 96:
      return 'Ninety-six';
    case 97:
      return 'Ninety-seven';
    case 98:
      return 'Ninety-eight';
    case 99:
      return 'Ninety-nine';
    case 100:
      return 'One hundred';
    default:
      return '';
  }
}



String spellNumber(int number) {
  switch (number) {
    case 0:
      return 'z-e-r-o-zero';
    case 1:
      return 'o-n-e-one';
    case 2:
      return 't-w-o-two';
    case 3:
      return 't-h-r-e-e-three';
    case 4:
      return 'f-o-u-r-four';
    case 5:
      return 'f-i-v-e-five';
    case 6:
      return 's-i-x-six';
    case 7:
      return 's-e-v-e-n-seven';
    case 8:
      return 'e-i-g-h-t-eight';
    case 9:
      return 'n-i-n-e-nine';
    case 10:
      return 't-e-n-ten';
    case 11:
      return 'e-l-e-v-e-n-eleven';
    case 12:
      return 't-w-e-l-v-e-twelve';
    case 13:
      return 't-h-i-r-t-e-e-n-thirteen';
    case 14:
      return 'f-o-u-r-t-e-e-n-fourteen';
    case 15:
      return 'f-i-f-t-e-e-n-fifteen';
    case 16:
      return 's-i-x-t-e-e-n-sixteen';
    case 17:
      return 's-e-v-e-n-t-e-e-n-seventeen';
    case 18:
      return 'e-i-g-h-t-e-e-n-eighteen';
    case 19:
      return 'n-i-n-e-t-e-e-n-nineteen';
    case 20:
      return 't-w-e-n-t-y-twenty';
    case 21:
      return 't-w-e-n-t-y-o-n-e-twenty-one';
    case 22:
      return 't-w-e-n-t-y-t-w-o-twenty-two';
    case 23:
      return 't-w-e-n-t-y-t-h-r-e-e-twenty-three';
    case 24:
      return 't-w-e-n-t-y-f-o-u-r-twenty-four';
    case 25:
      return 't-w-e-n-t-y-f-i-v-e-twenty-five';
    case 26:
      return 't-w-e-n-t-y-s-i-x-twenty-six';
    case 27:
      return 't-w-e-n-t-y-s-e-v-e-n-twenty-seven';
    case 28:
      return 't-w-e-n-t-y-e-i-g-h-t-twenty-eight';
    case 29:
      return 't-w-e-n-t-y-n-i-n-e-twenty-nine';
    case 30:
      return 't-h-i-r-t-y-thirty';
    case 31:
      return 't-h-i-r-t-y-o-n-e-thirty-one';
    case 32:
      return 't-h-i-r-t-y-t-w-o-thirty-two';
    case 33:
      return 't-h-i-r-t-y-t-h-r-e-e-thirty-three';
    case 34:
      return 't-h-i-r-t-y-f-o-u-r-thirty-four';
    case 35:
      return 't-h-i-r-t-y-f-i-v-e-thirty-five';
    case 36:
      return 't-h-i-r-t-y-s-i-x-thirty-six';
    case 37:
      return 't-h-i-r-t-y-s-e-v-e-n-thirty-seven';
    case 38:
      return 't-h-i-r-t-y-e-i-g-h-t-thirty-eight';
    case 39:
      return 't-h-i-r-t-y-n-i-n-e-thirty-nine';
    case 40:
      return 'f-o-r-t-y-forty';
    case 41:
      return 'f-o-r-t-y-o-n-e-forty-one';
    case 42:
      return 'f-o-r-t-y-t-w-o-forty-two';
    case 43:
      return 'f-o-r-t-y-t-h-r-e-e-forty-three';
    case 44:
      return 'f-o-r-t-y-f-o-u-r-forty-four';
    case 45:
      return 'f-o-r-t-y-f-i-v-e-forty-five';
    case 46:
      return 'f-o-r-t-y-s-i-x-forty-six';
    case 47:
      return 'f-o-r-t-y-s-e-v-e-n-forty-seven';
    case 48:
      return 'f-o-r-t-y-e-i-g-h-t-forty-eight';
    case 49:
      return 'f-o-r-t-y-n-i-n-e-forty-nine';
    case 50:
      return 'f-i-f-t-y-fifty';
    case 51:
      return 'f-i-f-t-y-o-n-e-fifty-one';
    case 52:
      return 'f-i-f-t-y-t-w-o-fifty-two';
    case 53:
      return 'f-i-f-t-y-t-h-r-e-e-fifty-three';
    case 54:
      return 'f-i-f-t-y-f-o-u-r-fifty-four';
    case 55:
      return 'f-i-f-t-y-f-i-v-e-fifty-five';
    case 56:
      return 'f-i-f-t-y-s-i-x-fifty-six';
    case 57:
      return 'f-i-f-t-y-s-e-v-e-n-fifty-seven';
    case 58:
      return 'f-i-f-t-y-e-i-g-h-t-fifty-eight';
    case 59:
      return 'f-i-f-t-y-n-i-n-e-fifty-nine';
    case 60:
      return 's-i-x-t-y-sixty';
    case 61:
      return 's-i-x-t-y-o-n-e-sixty-one';
    case 62:
      return 's-i-x-t-y-t-w-o-sixty-two';
    case 63:
      return 's-i-x-t-y-t-h-r-e-e-sixty-three';
    case 64:
      return 's-i-x-t-y-f-o-u-r-sixty-four';
    case 65:
      return 's-i-x-t-y-f-i-v-e-sixty-five';
    case 66:
      return 's-i-x-t-y-s-i-x-sixty-six';
    case 67:
      return 's-i-x-t-y-s-e-v-e-n-sixty-seven';
    case 68:
      return 's-i-x-t-y-e-i-g-h-t-sixty-eight';
    case 69:
      return 's-i-x-t-y-n-i-n-e-sixty-nine';
    case 70:
      return 's-e-v-e-n-t-y-seventy';
    case 71:
      return 's-e-v-e-n-t-y-o-n-e-seventy-one';
    case 72:
      return 's-e-v-e-n-t-y-t-w-o-seventy-two';
    case 73:
      return 's-e-v-e-n-t-y-t-h-r-e-e-seventy-three';
    case 74:
      return 's-e-v-e-n-t-y-f-o-u-r-seventy-four';
    case 75:
      return 's-e-v-e-n-t-y-f-i-v-e-seventy-five';
    case 76:
      return 's-e-v-e-n-t-y-s-i-x-seventy-six';
    case 77:
      return 's-e-v-e-n-t-y-s-e-v-e-n-seventy-seven';
    case 78:
      return 's-e-v-e-n-t-y-e-i-g-h-t-seventy-eight';
    case 79:
      return 's-e-v-e-n-t-y-n-i-n-e-seventy-nine';
    case 80:
      return 'e-i-g-h-t-y-eighty';
    case 81:
      return 'e-i-g-h-t-y-o-n-e-eighty-one';
    case 82:
      return 'e-i-g-h-t-y-t-w-o-eighty-two';
    case 83:
      return 'e-i-g-h-t-y-t-h-r-e-e-eighty-three';
    case 84:
      return 'e-i-g-h-t-y-f-o-u-r-eighty-four';
    case 85:
      return 'e-i-g-h-t-y-f-i-v-e-eighty-five';
    case 86:
      return 'e-i-g-h-t-y-s-i-x-eighty-six';
    case 87:
      return 'e-i-g-h-t-y-s-e-v-e-n-eighty-seven';
    case 88:
      return 'e-i-g-h-t-y-e-i-g-h-t-eighty-eight';
    case 89:
      return 'e-i-g-h-t-y-n-i-n-e-eighty-nine';
    case 90:
      return 'n-i-n-e-t-y-ninety';
    case 91:
      return 'n-i-n-e-t-y-o-n-e-ninety-one';
    case 92:
      return 'n-i-n-e-t-y-t-w-o-ninety-two';
    case 93:
      return 'n-i-n-e-t-y-t-h-r-e-e-ninety-three';
    case 94:
      return 'n-i-n-e-t-y-f-o-u-r-ninety-four';
    case 95:
      return 'n-i-n-e-t-y-f-i-v-e-ninety-five';
    case 96:
      return 'n-i-n-e-t-y-s-i-x-ninety-six';
    case 97:
      return 'n-i-n-e-t-y-s-e-v-e-n-ninety-seven';
    case 98:
      return 'n-i-n-e-t-y-e-i-g-h-t-ninety-eight';
    case 99:
      return 'n-i-n-e-t-y-n-i-n-e-ninety-nine';
    case 100:
      return 'o-n-e-h-u-n-d-r-e-d-one hundred';
    default:
      return '';
  }
}
